# Brownian Bridge Diffusion Model Template(Pixel Space)
runner: "BBDMRunner"
tune: "tune_20"
training:
  n_epochs: 100
  save_interval: 20
  # sample_interval: 2
  validation_interval: 20
  accumulate_grad_batches: 2
  batch_size: 64
  val_frac: 0.1
  classifier_free_guidance_prob: 0.15 


testing:
  clip_denoised: False
  # sample_num: 5
  percentile_sampling: 0.2
  num_candidates: 128
  type_sampling : 'highest'
  #alpha: 0.95
  #classifier_free_guidance_weight: -3


task: 
  name: 'TFBind10-Exact-v0'
  normalize_y: True
  normalize_x: True

GP: 
  initial_lengthscale: 6.0
  initial_outputscale: 6.0
  noise: 1.e-2
  num_functions: 8
  num_gradient_steps: 50
  num_points: 1024
  sampling_from_GP_lr: 0.05
  delta_lengthscale: 0.25
  delta_variance: 0.25
  threshold_diff: 0.001

model:
  model_name: "BrownianBridge" # part of result path
  model_type: "BBDM" # specify a module
  latent_before_quant_conv: False
  normalize_latent: False
  only_load_latent_mean_std: False
  #model_load_path: "results/AntMorphology-Exact-v0/BrownianBridge/2024-08-26T16-48-38/checkpoint/top_model_epoch_100.pth" # model checkpoint path
  #optim_sche_load_path: "results/AntMorphology-Exact-v0/BrownianBridge/2024-08-26T16-48-38/checkpoint/top_optim_sche_epoch_100.pth" # optimizer scheduler checkpoint path

  EMA:
    use_ema: True
    ema_decay: 0.995
    update_ema_interval: 8 # step
    start_ema_step: 4000

  CondStageParams:
    n_stages: 2
    in_channels: 3
    out_channels: 3

  BB:
    optimizer:
      weight_decay: 0.000
      optimizer: 'Adam'
      lr: 1.e-3
      beta1: 0.9

    lr_scheduler:
      factor: 0.5
      patience: 200
      threshold: 0.0001
      cooldown: 200
      min_lr: 5.e-7

    params:
      mt_type: 'linear' # options {'linear', 'sin'}
      objective: 'grad' # options {'grad', 'noise', 'ysubx'}
      loss_type: 'l1' # options {'l1', 'l2'}

      skip_sample: True
      sample_type: 'linear' # options {"linear", "sin"}
      sample_step: 200

      num_timesteps: 1000 # timesteps
      eta: 1.0 # DDIM reverse process eta
      max_var: 1.0 # maximum variance

      MLPParams:
        image_size: 30
        hidden_size: 1024
        condition_key: "SpatialRescaler" # options {"SpatialRescaler", "first_stage", "nocond"}


      # UNetParams:
      #   image_size: 512
      #   in_channels: 6
      #   model_channels: 128
      #   out_channels: 3
      #   num_res_blocks: 2
      #   attention_resolutions: !!python/tuple
      #     - 32
      #     - 16
      #     - 8
      #   channel_mult: !!python/tuple
      #     - 1
      #     - 4
      #     - 8
      #   conv_resample: True
      #   dims: 2
      #   num_heads: 8
      #   num_head_channels: 64
      #   use_scale_shift_norm: True
      #   resblock_updown: True
      #   use_spatial_transformer: False
      #   context_dim:
      #   condition_key: "SpatialRescaler" # options {"SpatialRescaler", "first_stage", "nocond"}